# Generated by Django 2.1.4 on 2019-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='userimg')),
            ],
        ),
    ]
