# Generated by Django 2.1.4 on 2019-01-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20190118_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='null', upload_to='userimg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
