# Generated by Django 2.1.4 on 2019-01-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20190118_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('con', models.CharField(max_length=20000, verbose_name='内容')),
                ('aname', models.CharField(max_length=20, verbose_name='作者')),
            ],
        ),
    ]
